# Generated by Django 4.2.30 on 2026-04-12 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0002_initial'),
        ('salas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='dispositivos.device'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('name', 'admin')},
        ),
    ]
