# Generated by Django 4.2.30 on 2026-04-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_active_subscription_per_user',
        ),
    ]
