# Generated by Django 4.2.30 on 2026-04-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_remove_subscription_unique_active_subscription_per_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': (models.OrderBy(models.F('expires_at'), descending=True, nulls_last=True),)},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
