# Generated by Django 4.2.30 on 2026-04-12 13:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unico', models.CharField(db_index=True, max_length=140, unique=True)),
                ('display_name', models.CharField(max_length=140)),
                ('fcm_token', models.CharField(blank=True, max_length=400)),
                ('is_locked', models.BooleanField(default=False)),
                ('battery_level', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('allow_emergency_calls', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('platform', models.CharField(blank=True, max_length=60)),
                ('os_version', models.CharField(blank=True, max_length=60)),
                ('app_version', models.CharField(blank=True, max_length=60)),
                ('technical_info', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='DeviceLockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOCK', 'Lock'), ('UNLOCK', 'Unlock'), ('AUTO_UNLOCK', 'Auto Unlock')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('was_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_events', to='dispositivos.device')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
